module.exports = {
  TOGGLE_SELECT: 'TOGGLE_SELECT',
  REQUEST_ACTIVITIES: 'REQUEST_ACTIVITIES',
  RECEIVE_ACTIVITIES: 'RECEIVE_ACTIVITIES',
  SEARCH_ACTIVITIES: 'SEARCH_ACTIVITIES',
  SCENE_ACTIVITIES: 'SCENE_ACTIVITIES',
  SCENE_ACTIVITY: 'SCENE_ACTIVITY'
};
